### ISSUE TITLE
Circular Import

### ISSUE THREAD

**Issue by CataRay** [enochkan/torch-metrics#33]
I am having trouble using this tool. It seems to hav e a bug. the simple example code:
```
from torch_metrics import Accuracy

## define metric ##
metric = torch_metrics.Accuracy(from_logits=False)
indx = 100
print(metric(p_all[indx,:,:,:], y_all[indx,:,:,:]))
```

Gives the error:

```
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-20-35cedb4ac57c> in <module>
----> 1 from torch_metrics import Accuracy
      2 
      3 ## define metric ##
      4 metric = torch_metrics.Accuracy(from_logits=False)
      5 indx = 100

/trials/Catalina/02_Projects/01_DeepLearning/_virtual_envs_/venv_Pytorch_coursera/lib/python3.8/site-packages/torch_metrics/__init__.py in <module>
----> 1 from torch_metrics import classification
      2 from torch_metrics import regression

ImportError: cannot import name 'classification' from partially initialized module 'torch_metrics' (most likely due to a circular import) (_virtual_envs_/venv_Pytorch_coursera/lib/python3.8/site-packages/torch_metrics/__init__.py)
```

I have installed using pip and working on a Ubuntu 20.4 with python3.7

**Comment by enochkan** [comment]
@CataRay thanks for raising this issue. Will have a look at it some time this week 👍

**Comment by enochkan** [comment]
Hey @CataRay sorry this totally went over my head. Have you tried this:

```from torch_metrics.classification import Accuracy```

seems to work for me.

**Comment by derrxb** [comment]
Hi, I can confirm that `from torch_metrics.classification import Accuracy` does not work with a clean install of the library.
